CREATE TABLE IF NOT EXISTS nexus (id SERIAL PRIMARY KEY, "name" TEXT NULL);
CREATE TABLE IF NOT EXISTS host_nexus (host_id INT, nexus_id INT, CONSTRAINT pk_host_nexus PRIMARY KEY (host_id, nexus_id), CONSTRAINT fk_host_nexus_host_id__id FOREIGN KEY (host_id) REFERENCES host(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_host_nexus_nexus_id__id FOREIGN KEY (nexus_id) REFERENCES nexus(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE SEQUENCE IF NOT EXISTS nexus_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
