CREATE TABLE IF NOT EXISTS variable (id SERIAL PRIMARY KEY, "name" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS integer_log (id BIGSERIAL PRIMARY KEY, variable_id INT NOT NULL, "value" INT NOT NULL, "time" BIGINT NOT NULL, CONSTRAINT fk_integer_log_variable_id__id FOREIGN KEY (variable_id) REFERENCES variable(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE SEQUENCE IF NOT EXISTS variable_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS integer_log_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
