CREATE TABLE IF NOT EXISTS json_log (id BIGSERIAL PRIMARY KEY, variable_id INT NOT NULL, "json" TEXT NOT NULL, "time" BIGINT NOT NULL, CONSTRAINT fk_json_log_variable_id__id FOREIGN KEY (variable_id) REFERENCES variable(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE SEQUENCE IF NOT EXISTS json_log_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
