ALTER TABLE story ADD coherence REAL NOT NULL;
ALTER TABLE story ADD vector vector(1536) NOT NULL;
ALTER TABLE story ALTER COLUMN "size" TYPE INT, ALTER COLUMN "size" SET NOT NULL;
ALTER TABLE story ALTER COLUMN score TYPE INT, ALTER COLUMN score SET NOT NULL;
ALTER TABLE chapter ADD story_distance REAL NULL;
