CREATE TABLE IF NOT EXISTS refresh_token (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL, token TEXT NOT NULL, created_at BIGINT NOT NULL, ttl INT NOT NULL, issuer TEXT NOT NULL, CONSTRAINT fk_refresh_token_user_id__id FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE SEQUENCE IF NOT EXISTS refresh_token_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
ALTER TABLE "user" DROP COLUMN venmo;
