ALTER TABLE "source" ADD score INT NULL;
ALTER TABLE feed_source ADD "source" JSON NOT NULL;
ALTER TABLE "source" DROP COLUMN lead_title;
ALTER TABLE feed_source DROP COLUMN source_id;
ALTER TABLE feed_source DROP COLUMN url;
ALTER TABLE feed_source DROP COLUMN host_core;
ALTER TABLE feed_source DROP COLUMN headline;
ALTER TABLE feed_source DROP COLUMN host_name;
ALTER TABLE feed_source DROP COLUMN host_logo;
ALTER TABLE feed_source DROP COLUMN citation_count;
ALTER TABLE feed_source DROP COLUMN word_count;
ALTER TABLE feed_source DROP COLUMN "section";
ALTER TABLE feed_source DROP COLUMN thumbnail;
ALTER TABLE feed_source DROP COLUMN seen_at;
ALTER TABLE feed_source DROP COLUMN published_at;
ALTER TABLE feed_source DROP COLUMN in_links;
ALTER TABLE feed_source DROP COLUMN scores;
ALTER TABLE feed_source DROP COLUMN authors;
ALTER TABLE feed_source DROP COLUMN latest_score;
DROP INDEX IF EXISTS feed_source_source_id_unique;
