CREATE TABLE IF NOT EXISTS "comment" (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL, "text" TEXT NOT NULL, "time" TIMESTAMP NOT NULL, CONSTRAINT fk_comment_user_id__id FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS huddle_comment (huddle_id BIGINT, comment_id BIGINT, CONSTRAINT pk_huddle_comment PRIMARY KEY (huddle_id, comment_id));
CREATE INDEX huddle_comment_huddle_id ON huddle_comment (huddle_id);
CREATE INDEX huddle_comment_comment_id ON huddle_comment (comment_id);
CREATE TABLE IF NOT EXISTS huddle_response (huddle_id BIGINT NOT NULL, user_id BIGINT NOT NULL, comment_id BIGINT NULL, response INT NOT NULL, datetime TIMESTAMP NOT NULL);
CREATE INDEX huddle_response_huddle_id ON huddle_response (huddle_id);
CREATE INDEX huddle_response_user_id ON huddle_response (user_id);
CREATE INDEX huddle_response_comment_id ON huddle_response (comment_id);
ALTER TABLE huddle_comment ADD CONSTRAINT fk_huddle_comment_huddle_id__id FOREIGN KEY (huddle_id) REFERENCES huddle(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle_comment ADD CONSTRAINT fk_huddle_comment_comment_id__id FOREIGN KEY (comment_id) REFERENCES "comment"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle_response ADD CONSTRAINT fk_huddle_response_huddle_id__id FOREIGN KEY (huddle_id) REFERENCES huddle(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle_response ADD CONSTRAINT fk_huddle_response_user_id__id FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle_response ADD CONSTRAINT fk_huddle_response_comment_id__id FOREIGN KEY (comment_id) REFERENCES "comment"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
CREATE SEQUENCE IF NOT EXISTS comment_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
ALTER TABLE chapter_source ADD relevance_huddle_id BIGINT NULL;
CREATE INDEX chapter_source_relevance_huddle_id ON chapter_source (relevance_huddle_id);
ALTER TABLE huddle ADD "options" TEXT[] NOT NULL;
ALTER TABLE chapter_source ADD CONSTRAINT fk_chapter_source_relevance_huddle_id__id FOREIGN KEY (relevance_huddle_id) REFERENCES huddle(id) ON DELETE SET NULL ON UPDATE RESTRICT;
