CREATE TABLE IF NOT EXISTS huddle (id BIGSERIAL PRIMARY KEY, chapter_id BIGINT NULL, source_id BIGINT NULL, initiator_id BIGINT NOT NULL, huddle_type INT NOT NULL, guide TEXT NOT NULL, "options" JSONB NOT NULL, consensus TEXT NULL, status INT NOT NULL, started_at TIMESTAMP NOT NULL, finished_at TIMESTAMP NOT NULL, recorded_at TIMESTAMP NULL);
CREATE INDEX huddle_chapter_id ON huddle (chapter_id);
CREATE INDEX huddle_source_id ON huddle (source_id);
CREATE INDEX huddle_initiator_id ON huddle (initiator_id);
CREATE TABLE IF NOT EXISTS huddle_comment (huddle_id BIGINT, comment_id BIGINT, CONSTRAINT pk_huddle_comment PRIMARY KEY (huddle_id, comment_id));
CREATE INDEX huddle_comment_huddle_id ON huddle_comment (huddle_id);
CREATE INDEX huddle_comment_comment_id ON huddle_comment (comment_id);
CREATE TABLE IF NOT EXISTS huddle_response (id BIGSERIAL PRIMARY KEY, huddle_id BIGINT NOT NULL, user_id BIGINT NOT NULL, comment_id BIGINT NULL, response TEXT NOT NULL, datetime TIMESTAMP NOT NULL);
CREATE INDEX huddle_response_huddle_id ON huddle_response (huddle_id);
CREATE INDEX huddle_response_user_id ON huddle_response (user_id);
CREATE INDEX huddle_response_comment_id ON huddle_response (comment_id);
ALTER TABLE huddle ADD CONSTRAINT fk_huddle_chapter_id__id FOREIGN KEY (chapter_id) REFERENCES chapter(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle ADD CONSTRAINT fk_huddle_source_id__id FOREIGN KEY (source_id) REFERENCES "source"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle ADD CONSTRAINT fk_huddle_initiator_id__id FOREIGN KEY (initiator_id) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle_comment ADD CONSTRAINT fk_huddle_comment_huddle_id__id FOREIGN KEY (huddle_id) REFERENCES huddle(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle_comment ADD CONSTRAINT fk_huddle_comment_comment_id__id FOREIGN KEY (comment_id) REFERENCES "comment"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle_response ADD CONSTRAINT fk_huddle_response_huddle_id__id FOREIGN KEY (huddle_id) REFERENCES huddle(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle_response ADD CONSTRAINT fk_huddle_response_user_id__id FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE huddle_response ADD CONSTRAINT fk_huddle_response_comment_id__id FOREIGN KEY (comment_id) REFERENCES "comment"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
CREATE SEQUENCE IF NOT EXISTS huddle_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
ALTER TABLE news_article ADD CONSTRAINT fk_news_article_article_type_huddle_id__id FOREIGN KEY (article_type_huddle_id) REFERENCES huddle(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE chapter_source ADD CONSTRAINT fk_chapter_source_relevance_huddle_id__id FOREIGN KEY (relevance_huddle_id) REFERENCES huddle(id) ON DELETE SET NULL ON UPDATE RESTRICT;
DROP SEQUENCE IF EXISTS huddle_response_id_seq;
