CREATE TABLE IF NOT EXISTS vector_model (id SERIAL PRIMARY KEY, "name" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS source_vector (id BIGSERIAL PRIMARY KEY, source_id BIGINT NOT NULL, model_id INT NOT NULL, vector vector(1536) NOT NULL, CONSTRAINT fk_source_vector_source_id__id FOREIGN KEY (source_id) REFERENCES "source"(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_source_vector_model_id__id FOREIGN KEY (model_id) REFERENCES vector_model(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE SEQUENCE IF NOT EXISTS source_vector_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
ALTER TABLE feed ALTER COLUMN created_at TYPE TIMESTAMP, ALTER COLUMN created_at SET DEFAULT (NOW());
ALTER TABLE "source" DROP COLUMN embedding;
