CREATE TABLE IF NOT EXISTS source_cache (id SERIAL PRIMARY KEY, source_id BIGINT NOT NULL, score INT NOT NULL, created_at TIMESTAMP NOT NULL, "source" JSON NOT NULL, CONSTRAINT fk_source_cache_source_id__id FOREIGN KEY (source_id) REFERENCES "source"(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE SEQUENCE IF NOT EXISTS source_cache_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
